# Generated by Django 4.1.2 on 2022-11-29 10:05

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('catalog', '0004_alter_bookinstance_options'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='bookinstance',
            options={'ordering': ['due_back'], 'permissions': (('can mark returned', 'Set book returned'),)},
        ),
    ]
